/**
 * Basic example demonstrating Blueberry serialization with hand-written codecs.
 *
 * Mirrors `blueberry-serde-python/examples/basic.py`. Real applications get
 * these encode/decode bodies generated by `blueberry-compiler --emit-typescript`.
 */

import {
  BLUEBERRY_PORT,
  type Decoder,
  type Encoder,
  deserializeMessage,
  deserializePacket,
  emptyMessage,
  serializeMessage,
  serializePacket,
} from '../src/index.js';

interface SensorReading {
  sensorId: number;
  temperature: number;
  humidity: number;
  alertHigh: boolean;
  alertLow: boolean;
}

const encodeSensorReading: Encoder<SensorReading> = (w, f) => {
  w.writeU32(f.sensorId);
  w.fieldDelta();
  w.writeF32(f.temperature);
  w.fieldDelta();
  w.writeU16(f.humidity);
  w.fieldDelta();
  w.writeBool(f.alertHigh);
  w.fieldDelta();
  w.writeBool(f.alertLow);
  w.fieldDelta();
};

const decodeSensorReading: Decoder<SensorReading> = (r) => ({
  sensorId: r.readU32(),
  temperature: r.readF32(),
  humidity: r.readU16(),
  alertHigh: r.readBool(),
  alertLow: r.readBool(),
});

interface DeviceStatusU16 {
  deviceId: number;
  name: string;
  readings: number[];
  online: boolean;
  calibrated: boolean;
}

const encodeDeviceStatusU16: Encoder<DeviceStatusU16> = (w, f) => {
  w.writeU32(f.deviceId);
  w.fieldDelta();
  w.writeString(f.name);
  w.fieldDelta();
  const seq = w.beginSequence();
  for (const v of f.readings) seq.writeElement((sw) => sw.writeU16(v));
  seq.end();
  w.fieldDelta();
  w.writeBool(f.online);
  w.fieldDelta();
  w.writeBool(f.calibrated);
  w.fieldDelta();
};

const decodeDeviceStatusU16: Decoder<DeviceStatusU16> = (r) => {
  const deviceId = r.readU32();
  const name = r.readString();
  const seq = r.beginSequence();
  const readings: number[] = [];
  for (let i = 0; i < seq.count; i++) {
    readings.push(seq.readElement((sr) => sr.readU16()));
  }
  const online = r.readBool();
  const calibrated = r.readBool();
  return { deviceId, name, readings, online, calibrated };
};

function hexDump(data: Uint8Array, label = ''): void {
  if (label) console.log(`\n  ${label}`);
  for (let i = 0; i < data.length; i += 16) {
    const hex = Array.from(data.subarray(i, i + 16))
      .map((b) => b.toString(16).padStart(2, '0'))
      .join(' ');
    console.log(`  ${i.toString(16).padStart(4, '0')}: ${hex}`);
  }
}

function main(): void {
  console.log('='.repeat(60));
  console.log(' Blueberry Serde — TypeScript Example');
  console.log(
    `  Protocol port: ${BLUEBERRY_PORT} (0x${BLUEBERRY_PORT.toString(16).toUpperCase()})`,
  );
  console.log('='.repeat(60));

  const reading: SensorReading = {
    sensorId: 42,
    temperature: 23.5,
    humidity: 65,
    alertHigh: true,
    alertLow: false,
  };
  console.log(`\nSensorReading:`, reading);

  const msg = serializeMessage(reading, 0x01, 0x42, encodeSensorReading);
  const pkt = serializePacket([msg]);
  hexDump(pkt, 'Packet bytes:');

  const { header: pktHdr, messages } = deserializePacket(pkt);
  console.log(
    `  Packet length: ${pktHdr.lengthWords} words, CRC: 0x${pktHdr.crc.toString(16).toUpperCase().padStart(4, '0')}`,
  );

  const { fields: rt } = deserializeMessage(messages[0]!, decodeSensorReading);
  console.log(`  Roundtrip:`, rt);

  const device: DeviceStatusU16 = {
    deviceId: 100,
    name: 'sensor-alpha',
    readings: [1023, 2047, 4095],
    online: true,
    calibrated: false,
  };
  console.log(`\nDeviceStatus (u16 readings):`, device);
  const devMsg = serializeMessage(device, 0x01, 0x42, encodeDeviceStatusU16);
  const devPkt = serializePacket([devMsg]);
  hexDump(devPkt, 'Packet bytes:');
  const { messages: devMessages } = deserializePacket(devPkt);
  const { fields: rtDev } = deserializeMessage(devMessages[0]!, decodeDeviceStatusU16);
  console.log(`  Roundtrip:`, rtDev);

  console.log('\nEmpty message (request-response mode):');
  const empty = emptyMessage(0x01, 0x42);
  hexDump(serializePacket([empty]), 'Packet bytes:');

  console.log('\nMultiple messages in one packet:');
  const multi = serializePacket([msg, devMsg]);
  hexDump(multi, 'Packet bytes:');
  const { header: mhdr, messages: mmsgs } = deserializePacket(multi);
  console.log(`  Packet has ${mmsgs.length} messages, ${mhdr.lengthWords} words`);
}

main();
